# Generated by Django 4.1.4 on 2023-07-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_room_image_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(null=True,blank=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.ForeignKey(null=True,blank=True, on_delete=django.db.models.deletion.CASCADE, to='note.departments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='semester',
            field=models.ForeignKey(null=True,blank=True, on_delete=django.db.models.deletion.CASCADE, to='note.semester'),
            preserve_default=False,
        ),
    ]
