# Generated by Django 4.1.4 on 2023-09-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0013_alter_orderitem_quantity_alter_room_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='image',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='rate',
        ),
    ]
