# Generated by Django 4.1.4 on 2023-09-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0014_rename_image_room_avatar_rename_price_room_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='static/images'),
        ),
    ]
