# Generated by Django 4.2.3 on 2023-09-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0019_alter_room_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
