# Generated by Django 4.2.3 on 2023-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0023_order_updated_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
