# Generated by Django 4.2.3 on 2023-10-04 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0024_remove_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rate',
            field=models.PositiveIntegerField(default=False, validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
    ]
